config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  devise_for :users
  resources :questions, only: [
    :index, :show, :new, :edit, :create, :update, :destroy
  ] do
    resources :answers, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :answers
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :description, presence: true, length: {minimum: 50}
  validates_presence_of [:user, :question], presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :questions
  has_many :answers

  devise    :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true,
            format: { with: /\A[a-z0-9_.+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-.]+\z/ }
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id].to_i
    @answer.user = current_user
    if @answer.save
      flash[:notice] = "Answer saved!"
      redirect_to question_path(params[:question_id])
    else
      flash[:alert] = "Answer not saved, check length (must be at least 50 characters)"
      redirect_to question_path(params[:question_id])
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      flash[:notice] = 'Answer Updated!'
      redirect_to question_path(@answer.question_id)
    else
      flash[:alert] = 'Answer Not Updated'
      render question_path(@answer.question_id)
    end
  end

  def show
    binding.pry
    @answer = Answer.find(params[:id])
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:notice] = 'Answer deleted.'
    redirect_to question_path(@answer.question_id)
  end

  private
  def answer_params
    params.require(:answer).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :devise_permitted_parameters, if: :devise_controller?

  protected

  def devise_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    respond_to do |format|
      format.html
      format.json { render json: @question }
    end
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:notice] = 'Question added!'
      redirect_to @question
    else
      flash[:alert] = 'Question not added!'
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = 'Update saved!'
      redirect_to @question
    else
      flash[:alert] = 'Update not saved!'
      redirect_to edit_question_path
    end
  end

  def destroy
    id = params[:id]
    @question = Question.find(id)
    @question.destroy
    flash[:notice] = 'Question deleted.'
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true)
    return markdown.render(text).html_safe
  end
end

app/views/answers/edit.html.erb
<dl class="sub-nav">
  <dd class="active"><%= link_to '_home', root_path %></dd>
  <dd class="active"><%= link_to '_back', question_path(@answer.question_id) %></dd>
</dl>

<div class="title_header">
  _update your answer
</div>

<fieldset>
    <%= form_for @answer do |f| %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.submit "Save changes" %>
    <% end %>
</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>_rescue mission</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="container">

  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "_rescue mission", root_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active">
        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </li>
    </ul>
  </section>
  </nav>

  <% if notice %>
    <div class="notice"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert"><%= alert %></div>
  <% end %>

  <%= yield %>

  </div>
  </body>
</html>

app/views/questions/edit.html.erb
<dl class="sub-nav">
  <dd class="active"><%= link_to '_home', root_path %></dd>
  <dd class="active"><%= link_to '_back', question_path(@question) %></dd>
</dl>

<div class="title_header">
  _update your question
</div>

<fieldset>
    <%= form_for @question do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.submit "Save changes" %>
    <% end %>
</fieldset>

app/views/questions/index.html.erb
<div class="title_header">
  _recent question(s)
</div>

<fieldset>
  <div class="questions">
    <% @questions.order(created_at: :desc).each do |question| %>
    <div class="questions panel">
      <%= '> '%><%= link_to question.title, question_path(question) %>
      <p class="username"><%= question.user.username %><%= ' | ' %><%= question.created_at %></p>
    </div>
    <% end %>
  </div>
</fieldset>

<dl class="sub-nav">
  <dd class="active"><%= link_to '_new question', new_question_path %></dd>
</dl>

app/views/questions/new.html.erb
<dl class="sub-nav">
  <dd class="active"><%= link_to '_home', root_path %></dd>
</dl>

<div class="title_header">
  _new question
</div>

<fieldset>
  <%= form_for @question do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.submit "Add Question" %>
  <% end %>
</fieldset>

app/views/questions/show.html.erb
<dl class="sub-nav">
  <dd class="active"><%= link_to '_home', root_path %></dd>
  <dd class="active"><%= link_to '_edit', edit_question_path %></dd>
  <dd class="active" id="delete"><%= link_to '_delete', '/questions/' + @question.to_param, method: :delete %></dd>
</dl>

<div class="title">
<%= @question.title %>
<p class="username"><%= '> ' %><%= @question.user.username %><%= ' | ' %><%= @question.created_at %></p></p>
</div>

<div class="description panel">
<p><%= @question.description %></p>
</div>

<fieldset>
  <legend>_answer(s)</legend>

  <div class="answers">
    <% @question.answers.each do |answer| %>
    <div class="answers panel">
      <p><%= link_to '_edit', edit_question_answer_path(@question, answer) %><%= ' | ' %>
         <%= link_to '_delete', '/questions/' + answer.question_id.to_s + '/answers/' + answer.to_param, method: :delete %></p>
      <%= markdown(answer.description) %>
      <p class="username"><%= answer.user.username %><%= ' | ' %><%= answer.created_at %></p>
    </div>
    <% end %>
  </div>

  <fieldset>
      <%= form_for [@question, @answer] do |f| %>

      <%= f.label :description, "_submit an answer" %>
      <%= f.text_area :description %></br>

      <%= f.submit "_submit" %>
    <% end %>
  </fieldset>
</fieldset>